package mx.edu.ubicatec.ponymaps.models.ubicacion

class UbicacionProvider {
    companion object {
        val ubicacionesList = listOf<Ubicacion>(
            Ubicacion("A", ""),
            Ubicacion("B", ""),
            Ubicacion("C", ""),
            Ubicacion("CH", ""),
            Ubicacion("D", ""),
            Ubicacion("E", ""),
            Ubicacion("F", ""),
            Ubicacion("G", ""),
            Ubicacion("H", ""),
            Ubicacion("I", ""),
            Ubicacion("J", ""),
            Ubicacion("K", ""),
            Ubicacion("L", ""),
            Ubicacion("LL", ""),
            Ubicacion("M", ""),
            Ubicacion("N", ""),
            Ubicacion("Ñ", ""),
            Ubicacion("O", ""),
            Ubicacion("P", ""),
            Ubicacion("Q", ""),
            Ubicacion("R", ""),
            Ubicacion("S", ""),
            Ubicacion("T", ""),
            Ubicacion("U", ""),
            Ubicacion("V", ""),
            Ubicacion("W", ""),
            Ubicacion("X", ""),
            Ubicacion("Y", ""),
            Ubicacion("Z", ""),

            Ubicacion("S1", ""),
            Ubicacion("S2", ""),
            Ubicacion("S3", ""),
            Ubicacion("AA", ""),
            Ubicacion("AB", ""),
            Ubicacion("AC", ""),
            Ubicacion("AD", ""),
            Ubicacion("AE", ""),
            Ubicacion("AF", ""),
            Ubicacion("AG", ""),
            Ubicacion("AH", ""),

            Ubicacion("2A", ""),
            Ubicacion("2B", ""),
            Ubicacion("2C", ""),
            Ubicacion("2F", ""),
            Ubicacion("2G", ""),
            Ubicacion("2H", ""),
            Ubicacion("2J", ""),
            Ubicacion("3A", ""),
            Ubicacion("3B", "")

            /*Ubicacion("A", "Lorem Ipsum"),
            Ubicacion("B", "Lorem Ipsum"),
            Ubicacion("C", "Lorem Ipsum"),
            Ubicacion("CH", "Lorem Ipsum"),
            Ubicacion("D", "Lorem Ipsum"),
            Ubicacion("E", "Lorem Ipsum"),
            Ubicacion("F", "Lorem Ipsum"),
            Ubicacion("G", "Lorem Ipsum"),
            Ubicacion("H", "Lorem Ipsum"),
            Ubicacion("I", "Lorem Ipsum"),
            Ubicacion("J", "Lorem Ipsum"),
            Ubicacion("K", "Lorem Ipsum"),
            Ubicacion("L", "Lorem Ipsum"),
            Ubicacion("LL", "Lorem Ipsum"),
            Ubicacion("M", "Lorem Ipsum"),
            Ubicacion("N", "Lorem Ipsum"),
            Ubicacion("Ñ", "Lorem Ipsum"),
            Ubicacion("O", "Lorem Ipsum"),
            Ubicacion("P", "Lorem Ipsum"),
            Ubicacion("Q", "Lorem Ipsum"),
            Ubicacion("R", "Lorem Ipsum"),
            Ubicacion("S", "Lorem Ipsum"),
            Ubicacion("T", "Lorem Ipsum"),
            Ubicacion("U", "Lorem Ipsum"),
            Ubicacion("V", "Lorem Ipsum"),
            Ubicacion("W", "Lorem Ipsum"),
            Ubicacion("X", "Lorem Ipsum"),
            Ubicacion("Y", "Lorem Ipsum"),
            Ubicacion("Z", "Lorem Ipsum"),

            Ubicacion("S1", "Lorem Ipsum"),
            Ubicacion("S2", "Lorem Ipsum"),
            Ubicacion("S3", "Lorem Ipsum"),
            Ubicacion("AA", "Lorem Ipsum"),
            Ubicacion("AB", "Lorem Ipsum"),
            Ubicacion("AC", "Lorem Ipsum"),
            Ubicacion("AD", "Lorem Ipsum"),
            Ubicacion("AE", "Lorem Ipsum"),
            Ubicacion("AF", "Lorem Ipsum"),
            Ubicacion("AG", "Lorem Ipsum"),
            Ubicacion("AH", "Lorem Ipsum"),

            Ubicacion("2A", "Lorem Ipsum"),
            Ubicacion("2B", "Lorem Ipsum"),
            Ubicacion("2C", "Lorem Ipsum"),
            Ubicacion("2F", "Lorem Ipsum"),
            Ubicacion("2G", "Lorem Ipsum"),
            Ubicacion("2H", "Lorem Ipsum"),
            Ubicacion("2J", "Lorem Ipsum"),
            Ubicacion("3A", "Lorem Ipsum"),
            Ubicacion("3B", "Lorem Ipsum")*/
        )
    }
}